{% set name = "aws-sso-util" %}
{% set version = "4.30.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws_sso_util-{{ version }}.tar.gz
  sha256: cfdca8877e7ab0a2dd9e360af45e9cb11420f7f8c31cec2c3b12f41d0a4f7f3a

build:
  number: 1
  noarch: python
  entry_points:
    - aws-sso-util = aws_sso_util.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - click >=7.1.2,<9.0.0  # upstream pins to <8 but this seems to work
    - boto3 >=1.20.28,<2.0.0
    - pyyaml >=5.3.1,<6.0.0
    - jsonschema >=3.2.0,<4.0.0
    - aws-error-utils >=1.0.4,<2.0.0
    - python-dateutil >=2.8.1,<3.0.0
    - aws-sso-lib >=1.9.0,<2.0.0
    - requests  >=2.26.0,<3.0.0
    - python >=3.6,<4.0

test:
  imports:
    - aws_sso_util
    - aws_sso_util.cfn_lib
  commands:
    - pip check
    - aws-sso-util --help
  requires:
    - pip

about:
  home: https://github.com/benkehoe/aws-sso-util
  summary: Utilities to make AWS SSO easier
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - tdsmith
